#include "wx/wx.h"
#include "wx/button.h"

#include "ErrorFrame.h"
#include "ErrorIcon.h"

ErrorFrame::ErrorFrame(const wxString& title, const wxPoint& pos, const wxSize& size, long style)
       : wxFrame(NULL, -1, title, pos, size, style)
{
    /**
     * THE FOLLOWING CODE WAS GENERATED BY wxFormBuilder v3.3 Beta on Ubuntu 13.04
     * With the Following Adjustments:
     * - The messagesSizer declaration was moved to ErrorFrame.h
     * - The literal '450' was replaced by WRAP_LENGTH
     * - The wxBitmap for the error.png was replaced with wxMEMORY_BITMAP(errorIcon)
     */
    this->SetSizeHints( wxDefaultSize, wxDefaultSize );
    
    wxBoxSizer* masterSizer;
    masterSizer = new wxBoxSizer( wxVERTICAL );
    
    masterPanel = new wxPanel( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );
    wxBoxSizer* masterHBoxSizer;
    masterHBoxSizer = new wxBoxSizer( wxHORIZONTAL );
    
    wxBoxSizer* errorIconSizer;
    errorIconSizer = new wxBoxSizer( wxVERTICAL );
    
    warningIcon = new wxStaticBitmap( masterPanel, wxID_ANY, wxMEMORY_BITMAP(errorIcon), wxDefaultPosition, wxDefaultSize, 0 );
    errorIconSizer->Add( warningIcon, 0, wxALL, 15 );
    
    
    masterHBoxSizer->Add( errorIconSizer, 0, wxALIGN_CENTER_VERTICAL|wxALIGN_LEFT|wxALL, 5 );
    
    messageSizer = new wxBoxSizer( wxVERTICAL );
    
    messageLabel = new wxStaticText( masterPanel, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );
    messageLabel->Wrap( WRAP_LENGTH );
    messageSizer->Add( messageLabel, 0, wxALIGN_LEFT|wxALL|wxEXPAND, 10 );
    
    okButton = new wxButton( masterPanel, myID_OK, wxT("Ok"), wxDefaultPosition, wxDefaultSize, 0 );
    messageSizer->Add( okButton, 0, wxALIGN_RIGHT|wxALL, 5 );
    
    
    masterHBoxSizer->Add( messageSizer, 0, wxALL, 5 );
    
    
    masterPanel->SetSizer( masterHBoxSizer );
    masterPanel->Layout();
    masterHBoxSizer->Fit( masterPanel );
    masterSizer->Add( masterPanel, 1, wxEXPAND | wxALL, 5 );
    
    
    this->SetSizer( masterSizer );
    this->Layout();
    masterSizer->Fit( this );
    
    this->Centre( wxBOTH );

    /**
     * End Generated Code
     */
    
    Connect(myID_OK, wxEVT_COMMAND_BUTTON_CLICKED, wxCommandEventHandler(ErrorFrame::OnOk));
}

ErrorFrame::~ErrorFrame()
{

}

void ErrorFrame::SetErrorMessage(wxString& errorMsg)
{
    messageLabel->SetLabel(errorMsg);
    messageLabel->Wrap( WRAP_LENGTH );

    messageSizer->Layout();
    this->Fit();
}

void ErrorFrame::OnOk(wxCommandEvent& event)
{
    Close(true);
}
