INSERT OR REPLACE INTO `setup`(`name`, `value`) VALUES
       ('p1enabled', 'true'),       
       ('p1name', 'Player 1'),       
       ('p1pushkey', 'Spacebar'),       
       ('p1leftkey', 'Left'),       
       ('p1rightkey', 'Right'),       
       ('p1upkey', 'Up'),       
       ('p1downkey', 'Down'),       
       ('p1type', 'Human'),       
       ('p2enabled', 'true'),       
       ('p2name', 'Player 2'),       
       ('p2pushkey', 'Spacebar'),       
       ('p2leftkey', 'Left'),       
       ('p2rightkey', 'Right'),       
       ('p2upkey', 'Up'),       
       ('p2downkey', 'Down'),       
       ('p2type', 'Human'),       
       ('p3enabled', 'true'),       
       ('p3name', 'Player 2'),       
       ('p3pushkey', 'Spacebar'),       
       ('p3leftkey', 'Left'),       
       ('p3rightkey', 'Right'),       
       ('p3upkey', 'Up'),       
       ('p3downkey', 'Down'),       
       ('p3type', 'Human'),       
       ('p4enabled', 'true'),       
       ('p4name', 'Player 2'),       
       ('p4pushkey', 'Spacebar'),       
       ('p4leftkey', 'Left'),       
       ('p4rightkey', 'Right'),       
       ('p4upkey', 'Up'),       
       ('p4downkey', 'Down'),       
       ('p4type', 'Human'),       
       ('soundenabled', 'true'),       
       ('musicenabled', 'true'),       
       ('difficulty', 'Normal')

