#ifndef CONTENT_IDS_H
#define CONTENT_IDS_H

enum ContentIds
{
    /**
     * TEXTURES
     */
    CID_BORDER_TOP,
    CID_BORDER_BOTTOM,
    CID_BORDER_LEFT,
    CID_BORDER_RIGHT,

    CID_MENU_TITLE_IDLE,
    CID_MENU_TITLE_HOVER,
    CID_MENU_TITLE_PRESSED,
    CID_MENU_TITLE_DIMMED,

    CID_MENU_INSTRUCTIONS_1_IDLE,
    CID_MENU_INSTRUCTIONS_1_HOVER,
    CID_MENU_INSTRUCTIONS_1_PRESSED,

    CID_MENU_INSTRUCTIONS_2_IDLE,
    CID_MENU_INSTRUCTIONS_2_HOVER,
    CID_MENU_INSTRUCTIONS_2_PRESSED,

    CID_MENU_PAUSE_IDLE,
    CID_MENU_PAUSE_HOVER,
    CID_MENU_PAUSE_PRESSED,

    CID_MENU_NET_IDLE,
    CID_MENU_NET_HOVER,
    CID_MENU_NET_PRESSED,

    CID_MENU_THANKS_IDLE,
    CID_MENU_THANKS_HOVER,
    CID_MENU_THANKS_PRESSED,

    CID_PATTERNS,
    CID_PLAYERS,
    CID_BLOCKS,
    CID_PERCENT_BACKGROUND,
    CID_PERCENT_FOREGROUND,
    CID_NUMBERS

    /**
     * Sound Effects
     */
    
    
    /**
     * Music
     */
};

#endif
