#include "wx/wx.h"
#include "wx/button.h"

#include "JoinFrame.h"

JoinFrame::JoinFrame(const wxString& title, const wxPoint& pos, const wxSize& size, long style)
       : wxFrame(NULL, -1, title, pos, size, style)
{
    /**
     * THE FOLLOWING CODE WAS GENERATED BY wxFormBuilder v3.3 Beta on Ubuntu 13.04
     */
    this->SetSizeHints( wxDefaultSize, wxDefaultSize );
    
    wxBoxSizer* masterVBoxSizer;
    masterVBoxSizer = new wxBoxSizer( wxVERTICAL );
    
    masterPanel = new wxPanel( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );
    wxBoxSizer* joinVBoxSizer;
    joinVBoxSizer = new wxBoxSizer( wxVERTICAL );
    
    playersMsgLabel = new wxStaticText( masterPanel, wxID_ANY, wxT("There is 1 local player (All human)"), wxDefaultPosition, wxDefaultSize, 0 );
    playersMsgLabel->Wrap( -1 );
    joinVBoxSizer->Add( playersMsgLabel, 0, wxALL, 5 );
    
    wxBoxSizer* connectHBoxSizer;
    connectHBoxSizer = new wxBoxSizer( wxHORIZONTAL );
    
    connectLabel = new wxStaticText( masterPanel, wxID_ANY, wxT("Connect to host"), wxDefaultPosition, wxDefaultSize, 0 );
    connectLabel->Wrap( -1 );
    connectHBoxSizer->Add( connectLabel, 0, wxALIGN_CENTER_VERTICAL|wxALL, 5 );
    
    hostTextCtrl = new wxTextCtrl( masterPanel, wxID_ANY, wxEmptyString, wxDefaultPosition, wxDefaultSize, 0 );
    hostTextCtrl->SetMinSize( wxSize( 300,-1 ) );
    
    connectHBoxSizer->Add( hostTextCtrl, 0, wxALL, 5 );
    
    
    joinVBoxSizer->Add( connectHBoxSizer, 1, wxEXPAND, 5 );
    
    wxBoxSizer* buttonHBoxSizer;
    buttonHBoxSizer = new wxBoxSizer( wxHORIZONTAL );
    
    cancelButton = new wxButton( masterPanel, wxID_ANY, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    buttonHBoxSizer->Add( cancelButton, 0, wxALL, 5 );
    
    connectButton = new wxButton( masterPanel, wxID_ANY, wxT("Connect"), wxDefaultPosition, wxDefaultSize, 0 );
    buttonHBoxSizer->Add( connectButton, 0, wxALL, 5 );
    
    
    joinVBoxSizer->Add( buttonHBoxSizer, 1, wxALIGN_RIGHT, 5 );
    
    
    masterPanel->SetSizer( joinVBoxSizer );
    masterPanel->Layout();
    joinVBoxSizer->Fit( masterPanel );
    masterVBoxSizer->Add( masterPanel, 1, wxEXPAND | wxALL, 5 );
    
    
    this->SetSizer( masterVBoxSizer );
    this->Layout();
    masterVBoxSizer->Fit( this );
    
    this->Centre( wxBOTH );
}

JoinFrame::~JoinFrame()
{

}
