#include "wx/wx.h"
#include "wx/button.h"

#include "ZapFrame.h"
#include "StopIcon.h"

ZapFrame::ZapFrame(const wxString& title, const wxPoint& pos, const wxSize& size, long style)
       : wxFrame(NULL, -1, title, pos, size, style)
{
    /**
     * THE FOLLOWING CODE WAS GENERATED BY wxFormBuilder v3.3 Beta on Ubuntu 13.04
     */
    this->SetSizeHints( wxDefaultSize, wxDefaultSize );
    
    wxBoxSizer* masterSizer;
    masterSizer = new wxBoxSizer( wxHORIZONTAL );
    
    masterPanel = new wxPanel( this, wxID_ANY, wxDefaultPosition, wxDefaultSize, wxTAB_TRAVERSAL );
    wxBoxSizer* masterHBoxSizer;
    masterHBoxSizer = new wxBoxSizer( wxHORIZONTAL );
    
    wxBoxSizer* leftSizer;
    leftSizer = new wxBoxSizer( wxVERTICAL );
    
    stopIcon = new wxStaticBitmap( masterPanel, wxID_ANY, wxMEMORY_BITMAP(stopIconData), wxDefaultPosition, wxDefaultSize, 0 );
    leftSizer->Add( stopIcon, 0, 0, 5 );
    
    
    masterHBoxSizer->Add( leftSizer, 0, wxALL, 20 );
    
    wxBoxSizer* rightSizer;
    rightSizer = new wxBoxSizer( wxVERTICAL );
    
    clearMsgLabel = new wxStaticText( masterPanel, wxID_ANY, wxT("Are you sure you want to clear the high scores?"), wxDefaultPosition, wxDefaultSize, 0 );
    clearMsgLabel->Wrap( -1 );
    rightSizer->Add( clearMsgLabel, 0, wxALL, 10 );
    
    wxBoxSizer* buttonSizer;
    buttonSizer = new wxBoxSizer( wxHORIZONTAL );
    
    cancelButton = new wxButton( masterPanel, wxID_ANY, wxT("Cancel"), wxDefaultPosition, wxDefaultSize, 0 );
    buttonSizer->Add( cancelButton, 0, wxALIGN_CENTER_VERTICAL|wxALIGN_RIGHT|wxALL, 5 );
    
    zapButton = new wxButton( masterPanel, wxID_ANY, wxT("Zap"), wxDefaultPosition, wxDefaultSize, 0 );
    zapButton->SetDefault(); 
    buttonSizer->Add( zapButton, 0, wxALIGN_CENTER_VERTICAL|wxALIGN_RIGHT|wxALL, 5 );
    
    
    rightSizer->Add( buttonSizer, 1, wxALIGN_RIGHT, 5 );
    
    
    masterHBoxSizer->Add( rightSizer, 0, wxALIGN_RIGHT|wxALL, 5 );
    
    
    masterPanel->SetSizer( masterHBoxSizer );
    masterPanel->Layout();
    masterHBoxSizer->Fit( masterPanel );
    masterSizer->Add( masterPanel, 1, wxEXPAND | wxALL, 5 );
    
    
    this->SetSizer( masterSizer );
    this->Layout();
    masterSizer->Fit( this );
    
    this->Centre( wxBOTH );
}

ZapFrame::~ZapFrame()
{

}
